---
- ansible.builtin.git:
    repo: https://github.com/go-nv/goenv.git
    dest: '{{ ansible_env.HOME }}/.goenv'
    version: master

- ansible.builtin.blockinfile:
    path: '{{ ansible_env.HOME }}/.bashrc'
    block: |
      export GOENV_ROOT="${HOME}/.goenv"
      export PATH="${GOENV_ROOT}/bin:${PATH}"
      eval "$(goenv init -)"
    state: present
    marker: "# {mark} ANSIBLE GOENV BLOCK"

- ansible.builtin.shell:
    cmd: source ~/.bashrc
    executable: /bin/bash
