---
- name: logrotate ... install
  ansible.builtin.apt:
    name: logrotate
    state: present

- name: logrotate ... configure for syslog
  ansible.builtin.copy:
    src: files/syslog
    dest: /etc/logrotate.d/syslog
    owner: root
    group: root
    mode: '0644'
