---
- ansible.builtin.git:
    repo: https://github.com/tfutils/tfenv.git
    dest: "{{ ansible_env.HOME }}/.tfenv"
    version: master

- ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: export PATH="${HOME}/.tfenv/bin:${PATH}"
    state: present
