---
- name: cywagon ... install
  ansible.builtin.shell:
    executable: /usr/bin/bash
    cmd: |
      curl -sL https://github.com/enuesaa/cywagon/releases/download/v0.0.5/install.sh | bash
      mv cywagon /usr/local/bin/cywagon
    creates: /usr/local/bin/cywagon

- name: cywagon ... create systemd unit file
  ansible.builtin.copy:
    src: cywagon.service
    dest: /etc/systemd/system/cywagon.service
    owner: root
    group: root
    mode: 0644

- name: cywagon ... reload
  ansible.builtin.command: systemctl daemon-reload

- name: cywagon ... create /var/www/html
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    owner: root
    group: root
    mode: 0777

- name: cywagon ... enable
  ansible.builtin.systemd:
    name: cywagon
    enabled: true
