---
# - ansible.builtin.shell:
#     cmd: systemctl list-unit-files
#     executable: /bin/bash

- name: cywagon ... install
  ansible.builtin.shell:
    cmd: go install github.com/enuesaa/cywagon@latest
    creates: /root/.goenv/shims/cywagon
    executable: /usr/bin/bash
