---
- name: cywagon ... install
  ansible.builtin.shell:
    executable: /usr/bin/bash
    cmd: |
      source /root/.bashrc
      go install github.com/enuesaa/cywagon@latest
    creates: /root/.goenv/shims/cywagon

- name: cywagon ... create systemd unit file
  ansible.builtin.copy:
    src: cywagon.service
    dest: /etc/systemd/system/cywagon.service
    owner: root
    group: root
    mode: 0644

- name: cywagon ... reload
  ansible.builtin.command: systemctl daemon-reload

- name: cywagon ... create /var/www/html
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    owner: root
    group: root
    mode: 0777
