---
- name: goenv ... git clone
  ansible.builtin.git:
    repo: https://github.com/go-nv/goenv.git
    version: master
    dest: /root/.goenv

- name: goenv ... write bashrc
  ansible.builtin.blockinfile:
    path: /root/.bashrc
    block: |
      export GOENV_ROOT="/root/.goenv"
      export PATH="${GOENV_ROOT}/bin:${PATH}"
      eval "$(goenv init -)"
    state: present
    marker: '# {mark} ANSIBLE GOENV BLOCK'

- name: goenv ... install go
  ansible.builtin.shell:
    executable: /usr/bin/bash
    cmd: |
      source /root/.bashrc
      goenv install 1.24.0 && goenv global 1.24.0
    creates: /root/.goenv/versions/1.24.0
