---
- name: goenv ... git clone
  ansible.builtin.git:
    repo: https://github.com/go-nv/goenv.git
    dest: '{{ ansible_env.HOME }}/.goenv'
    version: master

- name: goenv ... write bashrc
  ansible.builtin.blockinfile:
    path: '{{ ansible_env.HOME }}/.bashrc'
    block: |
      export GOENV_ROOT="${HOME}/.goenv"
      export PATH="${GOENV_ROOT}/bin:${PATH}"
      eval "$(goenv init -)"
    state: present
    marker: "# {mark} ANSIBLE GOENV BLOCK"

- name: goenv ... source bashrc
  ansible.builtin.shell:
    cmd: source ~/.bashrc
    executable: /usr/bin/bash

- name: goenv ... install go
  ansible.builtin.shell:
    cmd: goenv install 1.24.0 && goenv global 1.24.0
    creates: '{{ ansible_env.HOME }}/.goenv/versions/1.24.0'
    executable: /usr/bin/bash
