---
- name: pyenv ... git clone
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv.git
    dest: /root/.pyenv
    version: master

- name: pyenv ... write bashrc
  ansible.builtin.blockinfile:
    path: /root/.bashrc
    block: |
      export PYENV_ROOT="/root/.pyenv"
      export PATH="${PYENV_ROOT}/bin:${PATH}"
      eval "$(pyenv init --path)"
    state: present
    marker: '# {mark} ANSIBLE PYENV'
