---
- name: tfenv ... git clone
  ansible.builtin.git:
    repo: https://github.com/tfutils/tfenv.git
    dest: "{{ ansible_env.HOME }}/.tfenv"
    version: master

- name: tfenv ... write bash_profile
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bash_profile"
    line: export PATH="${HOME}/.tfenv/bin:${PATH}"
    state: present
