---
- name: tfenv ... git clone
  ansible.builtin.git:
    repo: https://github.com/tfutils/tfenv.git
    version: master
    dest: /root/.tfenv

- name: tfenv ... write bashrc
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    line: export PATH="/root/.tfenv/bin:${PATH}"
    state: present
