services:
  collector:
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    # see https://github.com/aws-observability/aws-otel-collector/blob/main/config/ecs/ecs-cloudwatch-xray.yaml
    command: ["--config=/etc/ecs/ecs-cloudwatch-xray.yaml"]
    # volumes:
    #   - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=aws.log.group.names=/aaa
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
    ports:
      - 4317:4317
      - 2000:2000
