receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  awsxray:
    region: ap-northeast-1

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [awsxray]
