receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  awsxray:
    indexed_attributes:
      - resolver
    region: ap-northeast-1
    aws_log_groups: ["/test"]

service:
  telemetry:
    logs:
      level: "DEBUG"
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [awsxray]
