services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'composer install && composer run rr-start'
    ports:
      - 8080:80
    volumes:
      - .:/app
    tty: true

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app

volumes:
  mysqldata:
