# pg_dump をローカルに入れるのが面倒だったので postgres コンテナで実行させている
# なので conf.yml とかちょっといびつ

services:
  postgres:
    image: postgres:13
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 30s
      interval: 10s
      retries: 3
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d/
      - ./conf.yml:/conf.yml
    ports:
      - 5432:5432
    depends_on:
      - dest
      - minio

  dest:
    image: postgres:13
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 30s
      interval: 10s
      retries: 3
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - 5453:5432

  minio:
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    command: server --console-address ":9001" /data/minio/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - POSTGRES_DB=app
    ports:
      - 9000:9000
      - 9001:9001
