/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * aeroview
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { unref } from 'vue'

import type { PictureResource } from './models'

import { fetcher } from './client'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export type getPictureResponse200 = {
  data: PictureResource
  status: 200
}

export type getPictureResponseComposite = getPictureResponse200

export type getPictureResponse = getPictureResponseComposite & {
  headers: Headers
}

export const getGetPictureUrl = () => {
  return `/api/picture`
}

export const getPicture = async (
  options?: RequestInit,
): Promise<getPictureResponse> => {
  return fetcher<getPictureResponse>(getGetPictureUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetPictureQueryKey = () => {
  return ['api', 'picture'] as const
}

export const getGetPictureQueryOptions = <
  TData = Awaited<ReturnType<typeof getPicture>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getPicture>>, TError, TData>
  >
  request?: SecondParameter<typeof fetcher>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getGetPictureQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPicture>>> = ({
    signal,
  }) => getPicture({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPicture>>,
    TError,
    TData
  >
}

export type GetPictureQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPicture>>
>
export type GetPictureQueryError = unknown

export function useGetPicture<
  TData = Awaited<ReturnType<typeof getPicture>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPicture>>, TError, TData>
    >
    request?: SecondParameter<typeof fetcher>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetPictureQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >

  return query
}
