---
- hosts: localhost
  connection: local
  become: true
  gather_facts: false
  environment:
    HOME: "{{ ansible_env.HOME | default('/root') }}"
  
  tasks:
    - ansible.builtin.setup:
        gather_subset:
          - min

    - name: base
      ansible.builtin.import_tasks:
        file: ./tasks/base.yml

    - name: logrotate
      ansible.builtin.import_tasks:
        file: ./tasks/logrotate.yml

    - name: goenv
      ansible.builtin.import_tasks:
        file: ./tasks/goenv.yml

    - name: pyenv
      ansible.builtin.import_tasks:
        file: ./tasks/pyenv.yml

    - name: nvm
      ansible.builtin.import_tasks:
        file: ./tasks/nvm.yml

    - name: tfenv
      ansible.builtin.import_tasks:
        file: ./tasks/tfenv.yml

    - name: cloudflared
      ansible.builtin.import_tasks:
        file: ./tasks/cloudflared.yml

    - name: cywagon
      ansible.builtin.import_tasks:
        file: ./tasks/cywagon.yml
