receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  application_signals:
    region: ap-northeast-1

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [application_signals]
