- hosts: localhost
  become: true

  tasks:
    - community.general.timezone:
        name: Asia/Tokyo

    - ansible.builtin.import_tasks:
        file: ./tasks/apt.yml

    - ansible.builtin.import_tasks:
        file: ./tasks/logrotate.yml

    - ansible.builtin.import_tasks:
        file: ./tasks/goenv.yml

    - ansible.builtin.import_tasks:
        file: ./tasks/pyenv.yml

    - ansible.builtin.import_tasks:
        file: ./tasks/nvm.yml

    - ansible.builtin.import_tasks:
        file: ./tasks/tfenv.yml

    # - ansible.builtin.import_tasks:
    #     file: ./tasks/cywagon.yml
