---
- hosts: localhost
  connection: local
  become: true
  gather_facts: false

  tasks:
    - ansible.builtin.setup:
        gather_subset:
          - min

    - community.general.timezone:
        name: Asia/Tokyo

    - name: aptbase
      ansible.builtin.import_tasks:
        file: ./tasks/aptbase.yml

    - name: logrotate
      ansible.builtin.import_tasks:
        file: ./tasks/logrotate.yml

    - name: goenv
      ansible.builtin.import_tasks:
        file: ./tasks/goenv.yml

    - name: pyenv
      ansible.builtin.import_tasks:
        file: ./tasks/pyenv.yml

    - name: nvm
      ansible.builtin.import_tasks:
        file: ./tasks/nvm.yml

    - name: tfenv
      ansible.builtin.import_tasks:
        file: ./tasks/tfenv.yml
