/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * My First API
 * OpenAPI spec version: 0.1
 */

/**
 * A Picture
 */
export interface PictureResource {
  /** title */
  title?: string
  /** url */
  url?: string
}
