/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * My First API
 * OpenAPI spec version: 0.1
 */
import type { PictureResourceData } from './pictureResourceData'

/**
 * A Picture
 */
export interface PictureResource {
  data?: PictureResourceData
}
