services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      # pgrx build すると ./target/releases 配下の深いところにできて扱いづらいので、./target 配下へ移動する
      - ./target/pgrx-install/lib/postgresql:/usr/lib/postgresql/17/lib/
      - ./target/pgrx-install/share/postgresql/extension:/usr/share/postgresql/17/extension