services:
  builder:
    build:
      context: .
      dockerfile: builder.Dockerfile
    volumes:
      - .:/workdir

  # after build
  postgres:
    image: postgres:17.4-bookworm
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./target/release/pgrxtry-pg17/usr/lib/postgresql/17/lib/pgrxtry.so:/usr/lib/postgresql/17/lib/pgrxtry.so
      - ./target/release/pgrxtry-pg17/usr/share/postgresql/17/extension/pgrxtry--0.0.0.sql:/usr/share/postgresql/17/extension/pgrxtry--0.0.0.sql
      - ./target/release/pgrxtry-pg17/usr/share/postgresql/17/extension/pgrxtry.control:/usr/share/postgresql/17/extension/pgrxtry.control
