version: '3'

tasks:
  up:
    desc: build and up
    cmds:
      - docker compose build

      # create target dir and .so
      - docker compose run --rm builder cargo pgrx package

      # mount .so to postgres container
      - docker compose up

      # To create extension:
      # - docker compose exec postgres psql -Upostgres
      # - CREATE EXTENSION pgrxtry;
      # - SELECT hello_pgrxtry();
