services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app
    ports:
      - 3306:3306
    volumes:
      - ./dbinit.sql:/docker-entrypoint-initdb.d/init.sql
