services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - MEMORY_LIMIT=128M
      - UPLOAD_LIMIT=128M
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - mysql

volumes:
  mysqldata:
