services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=sampledb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sampledb"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgweb:
    image: sosedoff/pgweb
    ports:
      - 8081:8081
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PGWEB_DATABASE_URL=postgres://user:pass@db:5432/sampledb?sslmode=disable

