services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app
    volumes:
      - mysqldata:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

volumes:
  mysqldata:
