services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=testdb
    ports:
      - 5432:5432
    volumes:
      - ./dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql


