services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./public:/var/www/html/public
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: bash -c 'composer install && php-fpm'
    volumes:
      - .:/var/www/html
    tty: true
