services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=coder
      - POSTGRES_PASSWORD=coderpass
      - POSTGRES_DB=coder
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
