services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - grafanadata:/var/lib/grafana
    depends_on:
      - tempo

  tempo:
    image: grafana/tempo:latest
    command: [--config.file=/etc/tempo.yml]
    volumes:
      - ./tempo.yml:/etc/tempo.yml
    ports:
      - 3200:3200
      - 4318:4318

volumes:
  grafanadata:
