services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    ports:
      - 8978:8978
    depends_on:
      - db
    environment:
      - CB_ADMIN_NAME=admin
      - CB_ADMIN_PASSWORD=admin
      - CB_AUTH_ENABLED=false
    volumes:
      - cloudbeaverdata:/opt/cloudbeaver/workspace

volumes:
  postgresdata:
  cloudbeaverdata:
