/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1dLZSDdyMvK6ejRBB7MCSN

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsz7UbWHp1J9 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: z7UB_w-hp1j9/globalVariant
import {
  ExperimentValue,
  useExperiment
} from "./PlasmicGlobalVariant__Experiment"; // plasmic-import: QigieynZSFnO/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsz7UbWHp1J9,
  experiment: useExperiment
});
